package AssetManagement.AssetManagement.enums;

public enum AssetType {
    LAPTOP,
    DESKTOP,
    MOBILE,
    PRINTER,
    SERVER,
    NETWORK_DEVICE,
    SOFTWARE,
    OTHERS,
    CCTV,
    COMPUTER,
    EQUIPMENT,
    FIREWALL,
    INTANGIBLE,
    ASSETS,
    IPAD, KIOSK,
     NETWORK, DEVICES, PRINTERS, PROJECTOR, TAB, TOUGHBOOK_ODIS,
    UPS, UPS_BATTERIES, VEHICLES, XENTRY_DIAGNOSTIC_DEVICE
    }
